# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

added_files = [
     ( 'bomb', 'bomb' ),
     ( 'explosion', 'explosion' ),
     ( 'ghost', 'ghost' ),
     ( 'happycat', 'happycat' ),
     ( 'happymouse', 'happymouse' ),
     ( 'searching', 'searching' ),
     ( 'searching2', 'searching2' ),
     ( 'wool', 'wool' ),
     ( 'accept button.png', '.' ),
     ( 'back.png', '.' ),
     ( 'bomb.gif', '.' ),
     ( 'Bomber.png', '.' ),
     ( 'cat.png', '.' ),
     ( 'Cheese Party.png', '.' ),
     ( 'Corporal.png', '.' ),
     ( 'Create Game LFO.png', '.' ),
     ( 'Create Game.png', '.' ),
     ( 'current_scene.png', '.' ),
     ( 'current_scene_copy.png', '.' ),
     ( 'Dark Cat.png', '.' ),
     ( 'defeat.png', '.' ),
     ( 'explosion.gif', '.' ),
     ( 'Factory1.png', '.' ),
     ( 'Factory2.png', '.' ),
     ( 'Factory3.png', '.' ),
     ( 'ghost.gif', '.' ),
     ( 'happycat.gif', '.' ),
     ( 'happymouse.gif', '.' ),
     ( 'hat.png', '.' ),
     ( 'Input Instructions button.png', '.' ),
     ( 'Input Instructions.png', '.' ),
     ( 'input_timer.png', '.' ),
     ( 'instructions button.png', '.' ),
     ( 'instructions.png', '.' ),
     ( 'interrupt.png', '.' ),
     ( 'looking for opponent.png', '.' ),
     ( 'MachineGun.png', '.' ),
     ( 'main menu button.png', '.' ),
     ( 'Main menu.png', '.' ),
     ( 'Map1.png', '.' ),
     ( 'mouse die.wav', '.' ),
     ( 'mouse eat.wav', '.' ),
     ( 'Mute.png', '.' ),
     ( 'new game.png', '.' ),
     ( 'no enter.gif', '.' ),
     ( 'piece sound1.wav', '.' ),
     ( 'piece sound2.wav', '.' ),
     ( 'private.png', '.' ),
     ( 'private_first_class.png', '.' ),
     ( 'private2.png', '.' ),
     ( 'privateSpaceShip.jpg', '.' ),
     ( 'PrivateSpaceShip.png', '.' ),
     ( 'round.png', '.' ),
     ( 'searching.gif', '.' ),
     ( 'searching2.gif', '.' ),
     ( 'Selected.png', '.' ),
     ( 'Sergeant.png', '.' ),
     ( 'speaker_on.png', '.' ),
     ( 'Specialist.png', '.' ),
     ( 'Text Box1.png', '.' ),
     ( 'Theme1.ogg', '.' ),
     ( 'victory.png', '.' ),
     ( 'way.png', '.' ),
     ( 'wierd.gif', '.' ),
     ( 'Witch.png', '.' ),
     ( 'wool.gif', '.' )
     ]

a = Analysis(['Client.py'],
             pathex=['C:\\python\\CPTD\\CPTD\\CPTD'],
             binaries=[],
             datas=added_files,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='Client',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
		  icon="Cheese.ico",
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
